pages:
    image:
      name: pandoc/core
      entrypoint: [""]
    tags:
        - docker
    script:
        - pushd .binder_landing_page
        - pandoc --metadata pagetitle="SAXS BioEn" -c pandoc.css -s index.md -o index.html
        - popd
        - mkdir public
        - cp .binder_landing_page/* public
    artifacts:
        paths:
            - public
    only:
        - master
